name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # O PROJECT_ID agora contém o ID NUMÉRICO (962245356193), conforme o Passo A
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: techmarket-api
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    # CORREÇÃO 1: Autentica SOMENTE com a chave JSON (credentials_json)
    # O Action 'auth@v2' não aceita o project_id neste passo.
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    # CORREÇÃO 2: Configura o ID do projeto em um passo separado após a autenticação.
    # Isso resolve o erro de que o Action 'auth' estava recebendo o project_id.
    - name: Set Project ID
      run: gcloud config set project ${{ env.PROJECT_ID }}

    - name: Configure Docker to use gcloud as a credential helper
      run: |
        gcloud auth configure-docker

    - name: Build and Push Container
      run: |
        docker build -t gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA .
        docker push gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --image gcr.io/$PROJECT_ID/$SERVICE:$GITHUB_SHA \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --port 5000 \
          --set-env-vars="FLASK_ENV=production"
